<?php

namespace TomatoPHP\FilamentIssues\Filament\Resources;

use Illuminate\Support\HtmlString;
use TomatoPHP\FilamentIssues\Filament\Resources\IssueResource\Pages;
use TomatoPHP\FilamentIssues\Filament\Resources\IssueResource\RelationManagers;
use TomatoPHP\FilamentIssues\Models\Issue;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class IssueResource extends Resource
{
    protected static ?string $model = Issue::class;

    protected static ?string $navigationIcon = 'bx-bullseye';


    public static function getNavigationGroup(): ?string
    {
        return "Content"; // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form;
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('title')
                    ->url(fn($record) => $record->url, true)
                    ->icon(fn($record) => $record->isPullRequest ? 'bx-git-pull-request' : 'bx-bullseye')
                    ->iconColor(fn($record) => $record->isPullRequest ? 'info' : 'warning')
                    ->description(fn($record) => "#" . $record->number . " opend " .  $record->createdAt->diffForHumans() . " in repository " . $record->repoName)
                    ->searchable(),
                Tables\Columns\ImageColumn::make('owner.profilePictureUrl')
                    ->label('By')
                    ->circular()
                    ->tooltip(fn($record) => $record->owner?->name)
                    ->url(fn($record) => $record->owner->url, true),
                Tables\Columns\TextColumn::make('labels.name')
                    ->label('Labels')
                    ->color('warning')
                    ->badge(),
                Tables\Columns\TextColumn::make('commentCount')
                    ->label('Comments')
                    ->icon('bxs-comment')
                    ->iconColor('primary')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\ToggleColumn::make('is_public')
                    ->label('Public')
                    ->sortable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->defaultSort('createdAt', 'desc')
            ->filters([
                Tables\Filters\SelectFilter::make('labels')
                    ->preload()
                    ->searchable()
                    ->relationship('labels', 'name'),
                Tables\Filters\SelectFilter::make('repo')
                    ->preload()
                    ->searchable()
                    ->relationship('repo', 'name'),
                Tables\Filters\SelectFilter::make('owner')
                    ->label('By')
                    ->preload()
                    ->searchable()
                    ->relationship('owner', 'name'),
                Tables\Filters\TernaryFilter::make('isPullRequest'),

            ])
            ->actions([

            ])
            ->bulkActions([

            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListIssues::route('/'),
        ];
    }
}
